package xxpha.oracle.apps.icx.sn1041.lov.server;

import java.util.Vector;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class StorListVOImpl extends OAViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public StorListVOImpl() {
    }
    
    public void initQuery(Number pOperatingUnit, Boolean executeQuery){
        int bindCount = 1;
        Vector parameters = new Vector(bindCount);
        parameters.addElement(pOperatingUnit);
        
        Object[] params = new Object[bindCount];
        parameters.copyInto(params);
        //setWhereClauseParams(params);
        if ((executeQuery != null) && (executeQuery.booleanValue())) {
            executeQuery();
            //next();
        }
    }
}
