package xxpha.oracle.apps.icx.sn1041.server;

import oracle.apps.fnd.framework.OAFwkConstants;
import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;
import oracle.apps.fnd.framework.server.OAViewObjectImpl;

import xxpha.oracle.apps.icx.sn1041.utils.Sn1041Utils;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ActiveCartVOImpl extends OAViewObjectImpl {
    public final String CLASS_NAME;

    /**This is the default constructor (do not remove)
     */
    public ActiveCartVOImpl() {
        this.CLASS_NAME = this.getClass().getName();
    }

    public void initQuery(Boolean executeQuery) {
        Sn1041Utils utils = Sn1041Utils.getInstance();

        if ((executeQuery != null) && (executeQuery.booleanValue())) {
            executeQuery();
            utils.writeDiagnostics((OAApplicationModuleImpl)getApplicationModule(), 
                                   CLASS_NAME + ".initQuery", 
                                   "After executeQuery - OK!", 
                                   OAFwkConstants.PROCEDURE);
        }
    }
}
