package xxpha.oracle.apps.icx.sn1041.server;

import java.util.Vector;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;

import xxpha.oracle.apps.icx.sn1041.server.common.AnalogVO;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AnalogVOImpl extends OAViewObjectImpl implements AnalogVO {
    public final String CLASS_NAME;

    /**This is the default constructor (do not remove)
     */
    public AnalogVOImpl() {
        this.CLASS_NAME = this.getClass().getName();
    }

    public void initQuery(long itemId, long currentStoreId, long currentCSId, long priceListId,
                          Boolean executeQuery) {
        int bindCount = 8;
        Vector parameters = new Vector(bindCount);
        parameters.addElement(itemId);
        parameters.addElement(itemId);
        parameters.addElement(priceListId);
        parameters.addElement(currentStoreId);
        parameters.addElement(currentStoreId);
        parameters.addElement(currentStoreId);
        parameters.addElement(currentStoreId);
        parameters.addElement(currentCSId);
        Object[] params = new Object[bindCount];
        parameters.copyInto(params);
        setWhereClauseParams(params);
        if ((executeQuery != null) && (executeQuery.booleanValue())) {
            executeQuery();
            //next();
        }
    }
}
