package xxpha.oracle.apps.icx.sn1041.server;

import oracle.apps.fnd.framework.OAFwkConstants;
import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;

import xxpha.oracle.apps.icx.sn1041.utils.Sn1041Utils;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DetailedAMImpl extends OAApplicationModuleImpl {
    /**This is the default constructor (do not remove)
     */
    public DetailedAMImpl() {
    }

    /**Sample main for debugging Business Components code using the tester.
     */
    public static void main(String[] args) { /* package name */
        /* Configuration Name */launchTester("xxpha.oracle.apps.icx.sn1041.server", 
                                             "DetailedAMLocal");
    }

    /**Container's getter for ReqQuantityDetailVO1
     */
    public ReqQuantityDetailVOImpl getReqQuantityDetailVO1() {
        return (ReqQuantityDetailVOImpl)findViewObject("ReqQuantityDetailVO1");
    }

    public void initDetailed(Long orgId, Long itemId, Long lStoreId, 
                             Long lCsId, String curr, Boolean executeQuery) {
        ReqQuantityDetailVOImpl vo = getReqQuantityDetailVO1();
        vo.initQuery(orgId.longValue(), itemId.longValue(), 
                     lStoreId.longValue(), lCsId.longValue(), curr, 
                     executeQuery);
    }

    /**Container's getter for ReqStatusDetailVO1
     */
    public ReqStatusDetailVOImpl getReqStatusDetailVO1() {
        return (ReqStatusDetailVOImpl)findViewObject("ReqStatusDetailVO1");
    }

    //          initStatusDetailed

    public void initStatusDetailed(Long orgId, Long itemId, /*Long lStoreId,
                             Long lCsId, String curr,*/Boolean executeQuery) {
        ReqStatusDetailVOImpl vo = getReqStatusDetailVO1(); /*
                     lStoreId.longValue(), lCsId.longValue(), curr, */
            vo.initQuery(orgId.longValue(), itemId.longValue(), executeQuery);
    }
}
