package xxpha.oracle.apps.icx.sn1041.server;

import com.sun.java.util.collections.Vector;

import oracle.apps.fnd.framework.OAFwkConstants;
import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;
import oracle.apps.fnd.framework.server.OAViewObjectImpl;

import oracle.jbo.domain.Number;

import xxpha.oracle.apps.icx.sn1041.utils.Sn1041Utils;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ParametersVOImpl extends OAViewObjectImpl {
    public final String CLASS_NAME;

    /**This is the default constructor (do not remove)
     */
    public ParametersVOImpl() {
        super();
        this.CLASS_NAME = this.getClass().getName();
    }

    public void initQuery(Number oeId, Boolean executeQuery) {
        Sn1041Utils.getInstance().writeDiagnostics((OAApplicationModuleImpl)getApplicationModule(), 
                                                   CLASS_NAME + ".initQuery", 
                                                   " - Start!", 
                                                   OAFwkConstants.PROCEDURE);
        int bindCount = 1;
        int clauseCount = 0;

        StringBuffer whereClause = new StringBuffer(100);
        Vector parameters = new Vector(bindCount);

        setWhereClauseParams(null); // Always reset

        //Org ID
        parameters.addElement(oeId);

        Object[] params = new Object[bindCount];
        parameters.copyInto(params);
        setWhereClauseParams(params);

        if ((executeQuery != null) && (executeQuery.booleanValue())) {
            executeQuery();
            next();
        }
    }
}
