package xxpha.oracle.apps.icx.sn1041.server;

import java.util.Vector;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ReqQuantityDetailVOImpl extends OAViewObjectImpl {
    private final String CLASS_NAME;

    /**This is the default constructor (do not remove)
     */
    public ReqQuantityDetailVOImpl() {
        super();
        this.CLASS_NAME = this.getClass().getName();
    }

    public void initQuery(long orgId, long itemId, long storeId, long csId, 
                          String curr, Boolean executeQuery) {
        StringBuilder sbWhere = new StringBuilder();
        Vector parameters;
        Object[] params;
        int bindCount;

        if ("Y".equals(curr)) {
            bindCount = 2;
            parameters = new Vector(bindCount);
            parameters.addElement(itemId);
            parameters.addElement(storeId);
            sbWhere.append("inventory_item_id = :1 AND organization_id = :2");
        } else {
            bindCount = 3;
            parameters = new Vector(bindCount);
            parameters.addElement(itemId);
            parameters.addElement(storeId);
            parameters.addElement(csId);
            sbWhere.append("inventory_item_id = :1 AND (organization_id not in  (:2, :3))");
        }
        params = new Object[bindCount];
        parameters.copyInto(params);
        setWhereClause(sbWhere.toString());
        setWhereClauseParams(params);
        if ((executeQuery != null) && (executeQuery.booleanValue())) {
            executeQuery();
            //next();
        }
    }
}
