package xxpha.oracle.apps.icx.sn1041.server;

import java.util.Vector;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;

import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ReqStatusDetailVOImpl extends OAViewObjectImpl {
    private final String CLASS_NAME;

    /**This is the default constructor (do not remove)
     */
    public ReqStatusDetailVOImpl() {
        super();
        this.CLASS_NAME = this.getClass().getName();
    }

    public void initQuery(long orgId, long itemId, /*long storeId, long csId,
                          String curr,*/Boolean executeQuery) {
        StringBuilder sbWhere = new StringBuilder();
        Vector parameters;
        Object[] params;
        int bindCount;

        /*
        if ("Y".equals(curr)) {
            bindCount = 2;
            parameters = new Vector(bindCount);
            parameters.addElement(itemId);
            parameters.addElement(storeId);
            sbWhere.append("inventory_item_id = :1 AND organization_id = :2");
        } else {
            bindCount = 3;
            parameters = new Vector(bindCount);
            parameters.addElement(itemId);
            parameters.addElement(storeId);
            parameters.addElement(csId);
            sbWhere.append("inventory_item_id = :1 AND (organization_id not in  (:2, :3))");
        }
        params = new Object[bindCount];
        parameters.copyInto(params);
        setWhereClause(sbWhere.toString());
        setWhereClauseParams(params);

        */
        setParamOrgId(new Number(orgId));
        setParamItemId(new Number(itemId));
        if ((executeQuery != null) && (executeQuery.booleanValue())) {
            executeQuery();
            //next();
        }
    }

    /**Gets the bind variable value for ParamOrgId
     */
    public Number getParamOrgId() {
        return (Number)getNamedWhereClauseParam("ParamOrgId");
    }

    /**Sets <code>value</code> for bind variable ParamOrgId
     */
    public void setParamOrgId(Number value) {
        setNamedWhereClauseParam("ParamOrgId", value);
    }

    /**Gets the bind variable value for ParamItemId
     */
    public Number getParamItemId() {
        return (Number)getNamedWhereClauseParam("ParamItemId");
    }

    /**Sets <code>value</code> for bind variable ParamItemId
     */
    public void setParamItemId(Number value) {
        setNamedWhereClauseParam("ParamItemId", value);
    }

    /**Gets the bind variable value for ParamReqId
     */
    public Number getParamReqId() {
        return (Number)getNamedWhereClauseParam("ParamReqId");
    }

    /**Sets <code>value</code> for bind variable ParamReqId
     */
    public void setParamReqId(Number value) {
        setNamedWhereClauseParam("ParamReqId", value);
    }

    /**Gets the bind variable value for ParamStatus
     */
    public String getParamStatus() {
        return (String)getNamedWhereClauseParam("ParamStatus");
    }

    /**Sets <code>value</code> for bind variable ParamStatus
     */
    public void setParamStatus(String value) {
        setNamedWhereClauseParam("ParamStatus", value);
    }

    /**Gets the bind variable value for ParamNeedDateFrom
     */
    public String getParamNeedDateFrom() {
        return (String)getNamedWhereClauseParam("ParamNeedDateFrom");
    }

    /**Sets <code>value</code> for bind variable ParamNeedDateFrom
     */
    public void setParamNeedDateFrom(String value) {
        setNamedWhereClauseParam("ParamNeedDateFrom", value);
    }

    /**Gets the bind variable value for ParamNeedDateTo
     */
    public String getParamNeedDateTo() {
        return (String)getNamedWhereClauseParam("ParamNeedDateTo");
    }

    /**Sets <code>value</code> for bind variable ParamNeedDateTo
     */
    public void setParamNeedDateTo(String value) {
        setNamedWhereClauseParam("ParamNeedDateTo", value);
    }

    /**Gets the bind variable value for ParamProjectId
     */
    public Number getParamProjectId() {
        return (Number)getNamedWhereClauseParam("ParamProjectId");
    }

    /**Sets <code>value</code> for bind variable ParamProjectId
     */
    public void setParamProjectId(Number value) {
        setNamedWhereClauseParam("ParamProjectId", value);
    }

    /**Gets the bind variable value for ParamPreparerId
     */
    public Number getParamPreparerId() {
        return (Number)getNamedWhereClauseParam("ParamPreparerId");
    }

    /**Sets <code>value</code> for bind variable ParamPreparerId
     */
    public void setParamPreparerId(Number value) {
        setNamedWhereClauseParam("ParamPreparerId", value);
    }
}
