package xxpha.oracle.apps.icx.sn1041.server;

import java.util.Vector;

import oracle.apps.fnd.framework.OAFwkConstants;
import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;
import oracle.apps.fnd.framework.server.OAViewObjectImpl;

import xxpha.oracle.apps.icx.sn1041.utils.Sn1041Utils;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SearchResultsVOImpl extends OAViewObjectImpl {
    public final String CLASS_NAME;

    /**This is the default constructor (do not remove)
     */
    public SearchResultsVOImpl() {
        super();
        this.CLASS_NAME = this.getClass().getName();
    }

    public void initQuery(long orgId, long currentStoreId, long currentCSId, 
                          Boolean executeQuery) {
        int bindCount = 12;

        int paramCounter = getWhereClauseParams().length;

        Sn1041Utils.getInstance().writeDiagnostics((OAApplicationModuleImpl)getApplicationModule(), 
                                                   CLASS_NAME + ".initQuery", 
                                                   " paramCounter = " + 
                                                   paramCounter, 
                                                   OAFwkConstants.PROCEDURE);

        Vector parameters = new Vector(bindCount);

        //1,2
        parameters.addElement(currentStoreId);
        parameters.addElement(currentCSId);
        //3,4,5
        parameters.addElement(orgId);
        parameters.addElement(currentCSId);
        parameters.addElement(currentCSId);        
        //6,7
        parameters.addElement(currentStoreId);
        parameters.addElement(currentStoreId);
        //8,9,10,11
        parameters.addElement(currentStoreId);
        parameters.addElement(currentCSId);
        parameters.addElement(currentStoreId);
        parameters.addElement(currentCSId);
        //12
        parameters.addElement(currentCSId);        

        Object[] params = new Object[bindCount];
        parameters.copyInto(params);
        setWhereClauseParams(params);
        if ((executeQuery != null) && (executeQuery.booleanValue())) {
            executeQuery();
            //next();
        }
    }
}
