package xxpha.oracle.apps.icx.sn1041.server;

import java.util.Vector;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SessionVOImpl extends OAViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public SessionVOImpl() {
    }

    public void dummy() {

    }

    public void initQuery(long userId, long respId, Boolean executeQuery) {
        
        int bindCount = 2;
        Vector parameters = new Vector(bindCount);
        parameters.addElement(userId);
        parameters.addElement(respId);
        Object[] params = new Object[bindCount];
        parameters.copyInto(params);
        setWhereClauseParams(params);
        if ((executeQuery != null) && (executeQuery.booleanValue())) {
            executeQuery();
            //next();
        }
    }
}
