package xxpha.oracle.apps.icx.sn1041.server;

import oracle.apps.fnd.framework.server.OAEntityDefImpl;
import oracle.apps.fnd.framework.server.OAEntityImpl;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SessionEOImpl extends OAEntityImpl {
    public static final int SID = 0;
    public static final int USERID = 1;
    public static final int RESPID = 2;
    public static final int LOGINID = 3;
    public static final int SESSIONDATE = 4;
    public static final int STOREID = 5;
    public static final int CREATEDBY = 6;
    public static final int CREATIONDATE = 7;
    public static final int LASTUPDATEDBY = 8;
    public static final int LASTUPDATEDATE = 9;
    public static final int LASTUPDATELOGIN = 10;
    public static final int OBJECTVERSIONNUMBER = 11;
    public static final int WIPENTITYID = 12;


    private static OAEntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public SessionEOImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = 
                    (OAEntityDefImpl)EntityDefImpl.findDefObject("xxpha.oracle.apps.icx.sn1041.server.SessionEO");
        }
        return mDefinitionObject;
    }

    /**Add attribute defaulting logic in this method.
     */
    public void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**Custom DML update/insert/delete logic here.
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }

    /**Gets the attribute value for SId, using the alias name SId
     */
    public Number getSId() {
        return (Number)getAttributeInternal(SID);
    }

    /**Sets <code>value</code> as the attribute value for SId
     */
    public void setSId(Number value) {
        setAttributeInternal(SID, value);
    }

    /**Gets the attribute value for UserId, using the alias name UserId
     */
    public Number getUserId() {
        return (Number)getAttributeInternal(USERID);
    }

    /**Sets <code>value</code> as the attribute value for UserId
     */
    public void setUserId(Number value) {
        setAttributeInternal(USERID, value);
    }

    /**Gets the attribute value for RespId, using the alias name RespId
     */
    public Number getRespId() {
        return (Number)getAttributeInternal(RESPID);
    }

    /**Sets <code>value</code> as the attribute value for RespId
     */
    public void setRespId(Number value) {
        setAttributeInternal(RESPID, value);
    }

    /**Gets the attribute value for LoginId, using the alias name LoginId
     */
    public Number getLoginId() {
        return (Number)getAttributeInternal(LOGINID);
    }

    /**Sets <code>value</code> as the attribute value for LoginId
     */
    public void setLoginId(Number value) {
        setAttributeInternal(LOGINID, value);
    }

    /**Gets the attribute value for SessionDate, using the alias name SessionDate
     */
    public Date getSessionDate() {
        return (Date)getAttributeInternal(SESSIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for SessionDate
     */
    public void setSessionDate(Date value) {
        setAttributeInternal(SESSIONDATE, value);
    }

    /**Gets the attribute value for StoreId, using the alias name StoreId
     */
    public Number getStoreId() {
        return (Number)getAttributeInternal(STOREID);
    }

    /**Sets <code>value</code> as the attribute value for StoreId
     */
    public void setStoreId(Number value) {
        setAttributeInternal(STOREID, value);
    }

    /**Gets the attribute value for CreatedBy, using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for CreationDate, using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**Gets the attribute value for ObjectVersionNumber, using the alias name ObjectVersionNumber
     */
    public Number getObjectVersionNumber() {
        return (Number)getAttributeInternal(OBJECTVERSIONNUMBER);
    }

    /**Sets <code>value</code> as the attribute value for ObjectVersionNumber
     */
    public void setObjectVersionNumber(Number value) {
        setAttributeInternal(OBJECTVERSIONNUMBER, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case SID:
            return getSId();
        case USERID:
            return getUserId();
        case RESPID:
            return getRespId();
        case LOGINID:
            return getLoginId();
        case SESSIONDATE:
            return getSessionDate();
        case STOREID:
            return getStoreId();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case OBJECTVERSIONNUMBER:
            return getObjectVersionNumber();
        case WIPENTITYID:
            return getWipEntityId();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case SID:
            setSId((Number)value);
            return;
        case USERID:
            setUserId((Number)value);
            return;
        case RESPID:
            setRespId((Number)value);
            return;
        case LOGINID:
            setLoginId((Number)value);
            return;
        case SESSIONDATE:
            setSessionDate((Date)value);
            return;
        case STOREID:
            setStoreId((Number)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        case OBJECTVERSIONNUMBER:
            setObjectVersionNumber((Number)value);
            return;
        case WIPENTITYID:
            setWipEntityId((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for WipEntityId, using the alias name WipEntityId
     */
    public Number getWipEntityId() {
        return (Number)getAttributeInternal(WIPENTITYID);
    }

    /**Sets <code>value</code> as the attribute value for WipEntityId
     */
    public void setWipEntityId(Number value) {
        setAttributeInternal(WIPENTITYID, value);
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number sId) {
        return new Key(new Object[]{sId});
    }
}
