package xxpha.oracle.apps.icx.sn1041.server;

import oracle.apps.fnd.framework.server.OAEntityDefImpl;
import oracle.apps.fnd.framework.server.OAEntityImpl;

import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Table5SourceEOImpl extends OAEntityImpl {
    public static final int LINENUM = 0;
    public static final int ITEMID = 1;
    public static final int DESCRIPTIONS = 2;
    public static final int ITEMCODE = 3;
    public static final int CATALOGNUM = 4;
    public static final int SUPDESCRIPTION = 5;
    public static final int UOM = 6;
    public static final int NEEDBYDATE = 7;
    public static final int QUANTITY = 8;
    public static final int UNITPRICE = 9;
    public static final int SUPPLIERID = 10;
    public static final int SOURCEORGANIZATIONID = 11;
    public static final int DESTORGANIZATIONID = 12;
    public static final int PREPARERID = 13;
    public static final int DELIVERTOLOCATIONID = 14;
    public static final int DELIVERTOREQUESTORID = 15;
    public static final int ORGID = 16;
    public static final int REQLINEID = 17;
    public static final int ISPROCESSED = 18;
    public static final int CSAVAILABLEQUANTITY = 19;
    public static final int SUPPLIER = 20;
    public static final int DELIVERYDATE = 21;
    public static final int DEACTIVATION = 22;
    public static final int INDEXNAME = 23;
    public static final int DELETELINE = 24;
    public static final int REQUISITIONTYPE = 25;
    public static final int CREATEDBY = 26;
    public static final int CREATIONDATE = 27;
    public static final int LASTUPDATEDBY = 28;
    public static final int LASTUPDATEDATE = 29;
    public static final int LASTUPDATELOGIN = 30;
    public static final int OBJECTVERSIONNUMBER = 31;
    public static final int REQITEMID = 32;
    public static final int REQHEADERNUM = 33;
    public static final int REQLINEQTY = 34;
    public static final int STATUS = 35;
    public static final int OPERATIONSEQNUM = 36;
    public static final int WIPENTITYID = 37;
    public static final int CFO = 38;
    public static final int MVZ = 39;
    public static final int WIPDATEREQUIRED = 40;
    public static final int WIPLOCATORID = 41;
    public static final int WIPSUBINVENTORY = 42;
    public static final int WIPGLDATE = 43;
    public static final int WIPBUYERNOTES = 44;
    public static final int WIPOLDATE = 45;
    public static final int WIPOLNUM = 46;
    public static final int WIPDUEDATE = 47;


    private static OAEntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public Table5SourceEOImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = 
                    (OAEntityDefImpl)EntityDefImpl.findDefObject("xxpha.oracle.apps.icx.sn1041.server.Table5SourceEO");
        }
        return mDefinitionObject;
    }

    /**Gets the attribute value for LineNum, using the alias name LineNum
     */
    public Number getLineNum() {
        return (Number)getAttributeInternal(LINENUM);
    }

    /**Sets <code>value</code> as the attribute value for LineNum
     */
    public void setLineNum(Number value) {
        setAttributeInternal(LINENUM, value);
    }

    /**Gets the attribute value for ItemId, using the alias name ItemId
     */
    public Number getItemId() {
        return (Number)getAttributeInternal(ITEMID);
    }

    /**Sets <code>value</code> as the attribute value for ItemId
     */
    public void setItemId(Number value) {
        setAttributeInternal(ITEMID, value);
    }

    /**Gets the attribute value for Descriptions, using the alias name Descriptions
     */
    public String getDescriptions() {
        return (String)getAttributeInternal(DESCRIPTIONS);
    }

    /**Sets <code>value</code> as the attribute value for Descriptions
     */
    public void setDescriptions(String value) {
        setAttributeInternal(DESCRIPTIONS, value);
    }

    /**Gets the attribute value for ItemCode, using the alias name ItemCode
     */
    public String getItemCode() {
        return (String)getAttributeInternal(ITEMCODE);
    }

    /**Sets <code>value</code> as the attribute value for ItemCode
     */
    public void setItemCode(String value) {
        setAttributeInternal(ITEMCODE, value);
    }

    /**Gets the attribute value for CatalogNum, using the alias name CatalogNum
     */
    public String getCatalogNum() {
        return (String)getAttributeInternal(CATALOGNUM);
    }

    /**Sets <code>value</code> as the attribute value for CatalogNum
     */
    public void setCatalogNum(String value) {
        setAttributeInternal(CATALOGNUM, value);
    }

    /**Gets the attribute value for SupDescription, using the alias name SupDescription
     */
    public String getSupDescription() {
        return (String)getAttributeInternal(SUPDESCRIPTION);
    }

    /**Sets <code>value</code> as the attribute value for SupDescription
     */
    public void setSupDescription(String value) {
        setAttributeInternal(SUPDESCRIPTION, value);
    }

    /**Gets the attribute value for Uom, using the alias name Uom
     */
    public String getUom() {
        return (String)getAttributeInternal(UOM);
    }

    /**Sets <code>value</code> as the attribute value for Uom
     */
    public void setUom(String value) {
        setAttributeInternal(UOM, value);
    }

    /**Gets the attribute value for NeedByDate, using the alias name NeedByDate
     */
    public Date getNeedByDate() {
        return (Date)getAttributeInternal(NEEDBYDATE);
    }

    /**Sets <code>value</code> as the attribute value for NeedByDate
     */
    public void setNeedByDate(Date value) {
        setAttributeInternal(NEEDBYDATE, value);
    }

    /**Gets the attribute value for Quantity, using the alias name Quantity
     */
    public Number getQuantity() {
        return (Number)getAttributeInternal(QUANTITY);
    }

    /**Sets <code>value</code> as the attribute value for Quantity
     */
    public void setQuantity(Number value) {
        setAttributeInternal(QUANTITY, value);
    }

    /**Gets the attribute value for UnitPrice, using the alias name UnitPrice
     */
    public Number getUnitPrice() {
        return (Number)getAttributeInternal(UNITPRICE);
    }

    /**Sets <code>value</code> as the attribute value for UnitPrice
     */
    public void setUnitPrice(Number value) {
        setAttributeInternal(UNITPRICE, value);
    }

    /**Gets the attribute value for SupplierId, using the alias name SupplierId
     */
    public Number getSupplierId() {
        return (Number)getAttributeInternal(SUPPLIERID);
    }

    /**Sets <code>value</code> as the attribute value for SupplierId
     */
    public void setSupplierId(Number value) {
        setAttributeInternal(SUPPLIERID, value);
    }

    /**Gets the attribute value for SourceOrganizationId, using the alias name SourceOrganizationId
     */
    public Number getSourceOrganizationId() {
        return (Number)getAttributeInternal(SOURCEORGANIZATIONID);
    }

    /**Sets <code>value</code> as the attribute value for SourceOrganizationId
     */
    public void setSourceOrganizationId(Number value) {
        setAttributeInternal(SOURCEORGANIZATIONID, value);
    }

    /**Gets the attribute value for DestOrganizationId, using the alias name DestOrganizationId
     */
    public Number getDestOrganizationId() {
        return (Number)getAttributeInternal(DESTORGANIZATIONID);
    }

    /**Sets <code>value</code> as the attribute value for DestOrganizationId
     */
    public void setDestOrganizationId(Number value) {
        setAttributeInternal(DESTORGANIZATIONID, value);
    }

    /**Gets the attribute value for PreparerId, using the alias name PreparerId
     */
    public Number getPreparerId() {
        return (Number)getAttributeInternal(PREPARERID);
    }

    /**Sets <code>value</code> as the attribute value for PreparerId
     */
    public void setPreparerId(Number value) {
        setAttributeInternal(PREPARERID, value);
    }

    /**Gets the attribute value for DeliverToLocationId, using the alias name DeliverToLocationId
     */
    public Number getDeliverToLocationId() {
        return (Number)getAttributeInternal(DELIVERTOLOCATIONID);
    }

    /**Sets <code>value</code> as the attribute value for DeliverToLocationId
     */
    public void setDeliverToLocationId(Number value) {
        setAttributeInternal(DELIVERTOLOCATIONID, value);
    }

    /**Gets the attribute value for DeliverToRequestorId, using the alias name DeliverToRequestorId
     */
    public Number getDeliverToRequestorId() {
        return (Number)getAttributeInternal(DELIVERTOREQUESTORID);
    }

    /**Sets <code>value</code> as the attribute value for DeliverToRequestorId
     */
    public void setDeliverToRequestorId(Number value) {
        setAttributeInternal(DELIVERTOREQUESTORID, value);
    }

    /**Gets the attribute value for OrgId, using the alias name OrgId
     */
    public Number getOrgId() {
        return (Number)getAttributeInternal(ORGID);
    }

    /**Sets <code>value</code> as the attribute value for OrgId
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**Gets the attribute value for ReqLineId, using the alias name ReqLineId
     */
    public Number getReqLineId() {
        return (Number)getAttributeInternal(REQLINEID);
    }


    /**Gets the attribute value for IsProcessed, using the alias name IsProcessed
     */
    public String getIsProcessed() {
        return (String)getAttributeInternal(ISPROCESSED);
    }

    /**Sets <code>value</code> as the attribute value for IsProcessed
     */
    public void setIsProcessed(String value) {
        setAttributeInternal(ISPROCESSED, value);
    }

    /**Gets the attribute value for CsAvailableQuantity, using the alias name CsAvailableQuantity
     */
    public Number getCsAvailableQuantity() {
        return (Number)getAttributeInternal(CSAVAILABLEQUANTITY);
    }

    /**Sets <code>value</code> as the attribute value for CsAvailableQuantity
     */
    public void setCsAvailableQuantity(Number value) {
        setAttributeInternal(CSAVAILABLEQUANTITY, value);
    }

    /**Gets the attribute value for Supplier, using the alias name Supplier
     */
    public String getSupplier() {
        return (String)getAttributeInternal(SUPPLIER);
    }

    /**Sets <code>value</code> as the attribute value for Supplier
     */
    public void setSupplier(String value) {
        setAttributeInternal(SUPPLIER, value);
    }

    /**Gets the attribute value for DeliveryDate, using the alias name DeliveryDate
     */
    public Number getDeliveryDate() {
        return (Number)getAttributeInternal(DELIVERYDATE);
    }

    /**Sets <code>value</code> as the attribute value for DeliveryDate
     */
    public void setDeliveryDate(Number value) {
        setAttributeInternal(DELIVERYDATE, value);
    }

    /**Gets the attribute value for Deactivation, using the alias name Deactivation
     */
    public String getDeactivation() {
        return (String)getAttributeInternal(DEACTIVATION);
    }

    /**Sets <code>value</code> as the attribute value for Deactivation
     */
    public void setDeactivation(String value) {
        setAttributeInternal(DEACTIVATION, value);
    }

    /**Gets the attribute value for DeleteLine, using the alias name DeleteLine
     */
    public String getDeleteLine() {
        return (String)getAttributeInternal(DELETELINE);
    }

    /**Sets <code>value</code> as the attribute value for DeleteLine
     */
    public void setDeleteLine(String value) {
        setAttributeInternal(DELETELINE, value);
    }

    /**Gets the attribute value for RequisitionType, using the alias name RequisitionType
     */
    public String getRequisitionType() {
        return (String)getAttributeInternal(REQUISITIONTYPE);
    }

    /**Sets <code>value</code> as the attribute value for RequisitionType
     */
    public void setRequisitionType(String value) {
        setAttributeInternal(REQUISITIONTYPE, value);
    }

    /**Gets the attribute value for CreatedBy, using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for CreationDate, using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**Gets the attribute value for ObjectVersionNumber, using the alias name ObjectVersionNumber
     */
    public Number getObjectVersionNumber() {
        return (Number)getAttributeInternal(OBJECTVERSIONNUMBER);
    }

    /**Sets <code>value</code> as the attribute value for ObjectVersionNumber
     */
    public void setObjectVersionNumber(Number value) {
        setAttributeInternal(OBJECTVERSIONNUMBER, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case LINENUM:
            return getLineNum();
        case ITEMID:
            return getItemId();
        case DESCRIPTIONS:
            return getDescriptions();
        case ITEMCODE:
            return getItemCode();
        case CATALOGNUM:
            return getCatalogNum();
        case SUPDESCRIPTION:
            return getSupDescription();
        case UOM:
            return getUom();
        case NEEDBYDATE:
            return getNeedByDate();
        case QUANTITY:
            return getQuantity();
        case UNITPRICE:
            return getUnitPrice();
        case SUPPLIERID:
            return getSupplierId();
        case SOURCEORGANIZATIONID:
            return getSourceOrganizationId();
        case DESTORGANIZATIONID:
            return getDestOrganizationId();
        case PREPARERID:
            return getPreparerId();
        case DELIVERTOLOCATIONID:
            return getDeliverToLocationId();
        case DELIVERTOREQUESTORID:
            return getDeliverToRequestorId();
        case ORGID:
            return getOrgId();
        case REQLINEID:
            return getReqLineId();
        case ISPROCESSED:
            return getIsProcessed();
        case CSAVAILABLEQUANTITY:
            return getCsAvailableQuantity();
        case SUPPLIER:
            return getSupplier();
        case DELIVERYDATE:
            return getDeliveryDate();
        case DEACTIVATION:
            return getDeactivation();
        case INDEXNAME:
            return getIndexName();
        case DELETELINE:
            return getDeleteLine();
        case REQUISITIONTYPE:
            return getRequisitionType();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case OBJECTVERSIONNUMBER:
            return getObjectVersionNumber();
        case REQITEMID:
            return getReqItemId();
        case REQHEADERNUM:
            return getReqHeaderNum();
        case REQLINEQTY:
            return getReqLineQty();
        case STATUS:
            return getStatus();
        case OPERATIONSEQNUM:
            return getOperationSeqNum();
        case WIPENTITYID:
            return getWipEntityId();
        case CFO:
            return getCfo();
        case MVZ:
            return getMvz();
        case WIPDATEREQUIRED:
            return getWipDateRequired();
        case WIPLOCATORID:
            return getWipLocatorId();
        case WIPSUBINVENTORY:
            return getWipSubinventory();
        case WIPGLDATE:
            return getWipGlDate();
        case WIPBUYERNOTES:
            return getWipBuyerNotes();
        case WIPOLDATE:
            return getWipOlDate();
        case WIPOLNUM:
            return getWipOlNum();
        case WIPDUEDATE:
            return getWipDueDate();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case LINENUM:
            setLineNum((Number)value);
            return;
        case ITEMID:
            setItemId((Number)value);
            return;
        case DESCRIPTIONS:
            setDescriptions((String)value);
            return;
        case ITEMCODE:
            setItemCode((String)value);
            return;
        case CATALOGNUM:
            setCatalogNum((String)value);
            return;
        case SUPDESCRIPTION:
            setSupDescription((String)value);
            return;
        case UOM:
            setUom((String)value);
            return;
        case NEEDBYDATE:
            setNeedByDate((Date)value);
            return;
        case QUANTITY:
            setQuantity((Number)value);
            return;
        case UNITPRICE:
            setUnitPrice((Number)value);
            return;
        case SUPPLIERID:
            setSupplierId((Number)value);
            return;
        case SOURCEORGANIZATIONID:
            setSourceOrganizationId((Number)value);
            return;
        case DESTORGANIZATIONID:
            setDestOrganizationId((Number)value);
            return;
        case PREPARERID:
            setPreparerId((Number)value);
            return;
        case DELIVERTOLOCATIONID:
            setDeliverToLocationId((Number)value);
            return;
        case DELIVERTOREQUESTORID:
            setDeliverToRequestorId((Number)value);
            return;
        case ORGID:
            setOrgId((Number)value);
            return;
        case REQLINEID:
            setReqLineId((Number)value);
            return;
        case ISPROCESSED:
            setIsProcessed((String)value);
            return;
        case CSAVAILABLEQUANTITY:
            setCsAvailableQuantity((Number)value);
            return;
        case SUPPLIER:
            setSupplier((String)value);
            return;
        case DELIVERYDATE:
            setDeliveryDate((Number)value);
            return;
        case DEACTIVATION:
            setDeactivation((String)value);
            return;
        case INDEXNAME:
            setIndexName((String)value);
            return;
        case DELETELINE:
            setDeleteLine((String)value);
            return;
        case REQUISITIONTYPE:
            setRequisitionType((String)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        case OBJECTVERSIONNUMBER:
            setObjectVersionNumber((Number)value);
            return;
        case REQITEMID:
            setReqItemId((Number)value);
            return;
        case OPERATIONSEQNUM:
            setOperationSeqNum((Number)value);
            return;
        case WIPENTITYID:
            setWipEntityId((Number)value);
            return;
        case CFO:
            setCfo((String)value);
            return;
        case MVZ:
            setMvz((String)value);
            return;
        case WIPDATEREQUIRED:
            setWipDateRequired((Date)value);
            return;
        case WIPLOCATORID:
            setWipLocatorId((Number)value);
            return;
        case WIPSUBINVENTORY:
            setWipSubinventory((String)value);
            return;
        case WIPGLDATE:
            setWipGlDate((Date)value);
            return;
        case WIPBUYERNOTES:
            setWipBuyerNotes((String)value);
            return;
        case WIPOLDATE:
            setWipOlDate((Date)value);
            return;
        case WIPOLNUM:
            setWipOlNum((String)value);
            return;
        case WIPDUEDATE:
            setWipDueDate((Date)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for IndexName, using the alias name IndexName
     */
    public String getIndexName() {
        return (String)getAttributeInternal(INDEXNAME);
    }

    /**Sets <code>value</code> as the attribute value for IndexName
     */
    public void setIndexName(String value) {
        setAttributeInternal(INDEXNAME, value);
    }

    /**Gets the attribute value for ReqItemId, using the alias name ReqItemId
     */
    public Number getReqItemId() {
        return (Number)getAttributeInternal(REQITEMID);
    }

    /**Sets <code>value</code> as the attribute value for ReqItemId
     */
    public void setReqItemId(Number value) {
        setAttributeInternal(REQITEMID, value);
    }

    /**Gets the attribute value for ReqHeaderNum, using the alias name ReqHeaderNum
     */
    public String getReqHeaderNum() {
        return (String)getAttributeInternal(REQHEADERNUM);
    }


    /**Gets the attribute value for ReqLineQty, using the alias name ReqLineQty
     */
    public Number getReqLineQty() {
        return (Number)getAttributeInternal(REQLINEQTY);
    }


    /**Gets the attribute value for Status, using the alias name Status
     */
    public String getStatus() {
        return (String)getAttributeInternal(STATUS);
    }


    /**Gets the attribute value for OperationSeqNum, using the alias name OperationSeqNum
     */
    public Number getOperationSeqNum() {
        return (Number)getAttributeInternal(OPERATIONSEQNUM);
    }

    /**Sets <code>value</code> as the attribute value for OperationSeqNum
     */
    public void setOperationSeqNum(Number value) {
        setAttributeInternal(OPERATIONSEQNUM, value);
    }

    /**Gets the attribute value for WipEntityId, using the alias name WipEntityId
     */
    public Number getWipEntityId() {
        return (Number)getAttributeInternal(WIPENTITYID);
    }

    /**Sets <code>value</code> as the attribute value for WipEntityId
     */
    public void setWipEntityId(Number value) {
        setAttributeInternal(WIPENTITYID, value);
    }

    /**Gets the attribute value for Cfo, using the alias name Cfo
     */
    public String getCfo() {
        return (String)getAttributeInternal(CFO);
    }

    /**Sets <code>value</code> as the attribute value for Cfo
     */
    public void setCfo(String value) {
        setAttributeInternal(CFO, value);
    }

    /**Gets the attribute value for Mvz, using the alias name Mvz
     */
    public String getMvz() {
        return (String)getAttributeInternal(MVZ);
    }

    /**Sets <code>value</code> as the attribute value for Mvz
     */
    public void setMvz(String value) {
        setAttributeInternal(MVZ, value);
    }

    /**Gets the attribute value for WipDateRequired, using the alias name WipDateRequired
     */
    public Date getWipDateRequired() {
        return (Date)getAttributeInternal(WIPDATEREQUIRED);
    }

    /**Sets <code>value</code> as the attribute value for WipDateRequired
     */
    public void setWipDateRequired(Date value) {
        setAttributeInternal(WIPDATEREQUIRED, value);
    }

    /**Gets the attribute value for WipLocatorId, using the alias name WipLocatorId
     */
    public Number getWipLocatorId() {
        return (Number)getAttributeInternal(WIPLOCATORID);
    }

    /**Sets <code>value</code> as the attribute value for WipLocatorId
     */
    public void setWipLocatorId(Number value) {
        setAttributeInternal(WIPLOCATORID, value);
    }

    /**Gets the attribute value for WipSubinventory, using the alias name WipSubinventory
     */
    public String getWipSubinventory() {
        return (String)getAttributeInternal(WIPSUBINVENTORY);
    }

    /**Sets <code>value</code> as the attribute value for WipSubinventory
     */
    public void setWipSubinventory(String value) {
        setAttributeInternal(WIPSUBINVENTORY, value);
    }

    /**Gets the attribute value for WipGlDate, using the alias name WipGlDate
     */
    public Date getWipGlDate() {
        return (Date)getAttributeInternal(WIPGLDATE);
    }

    /**Sets <code>value</code> as the attribute value for WipGlDate
     */
    public void setWipGlDate(Date value) {
        setAttributeInternal(WIPGLDATE, value);
    }

    /**Sets <code>value</code> as the attribute value for ReqLineId
     */
    public void setReqLineId(Number value) {
        setAttributeInternal(REQLINEID, value);
    }

    /**Gets the attribute value for WipBuyerNotes, using the alias name WipBuyerNotes
     */
    public String getWipBuyerNotes() {
        return (String)getAttributeInternal(WIPBUYERNOTES);
    }

    /**Sets <code>value</code> as the attribute value for WipBuyerNotes
     */
    public void setWipBuyerNotes(String value) {
        setAttributeInternal(WIPBUYERNOTES, value);
    }

    /**Gets the attribute value for WipOlDate, using the alias name WipOlDate
     */
    public Date getWipOlDate() {
        return (Date)getAttributeInternal(WIPOLDATE);
    }

    /**Sets <code>value</code> as the attribute value for WipOlDate
     */
    public void setWipOlDate(Date value) {
        setAttributeInternal(WIPOLDATE, value);
    }

    /**Gets the attribute value for WipOlNum, using the alias name WipOlNum
     */
    public String getWipOlNum() {
        return (String)getAttributeInternal(WIPOLNUM);
    }

    /**Sets <code>value</code> as the attribute value for WipOlNum
     */
    public void setWipOlNum(String value) {
        setAttributeInternal(WIPOLNUM, value);
    }

    /**Gets the attribute value for WipDueDate, using the alias name WipDueDate
     */
    public Date getWipDueDate() {
        return (Date)getAttributeInternal(WIPDUEDATE);
    }

    /**Sets <code>value</code> as the attribute value for WipDueDate
     */
    public void setWipDueDate(Date value) {
        setAttributeInternal(WIPDUEDATE, value);
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number reqItemId) {
        return new Key(new Object[]{reqItemId});
    }
}
