package xxpha.oracle.apps.icx.sn1041.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Table5SourceVORowImpl extends OAViewRowImpl {
    //public static final int ISSELECT2 = 35;
    //public static final int ISSELECT2_1 = 34;
    //public static final int ISSELECT2_1_1 = 34;
    public static final int LINENUM = 0;
    public static final int ITEMID = 1;
    public static final int DESCRIPTIONS = 2;
    public static final int ITEMCODE = 3;
    public static final int CATALOGNUM = 4;
    public static final int SUPDESCRIPTION = 5;
    public static final int UOM = 6;
    public static final int NEEDBYDATE = 7;
    public static final int QUANTITY = 8;
    public static final int UNITPRICE = 9;
    public static final int SUPPLIERID = 10;
    public static final int SOURCEORGANIZATIONID = 11;
    public static final int DESTORGANIZATIONID = 12;
    public static final int PREPARERID = 13;
    public static final int DELIVERTOLOCATIONID = 14;
    public static final int DELIVERTOREQUESTORID = 15;
    public static final int ORGID = 16;
    public static final int REQLINEID = 17;
    public static final int ISPROCESSED = 18;
    public static final int CSAVAILABLEQUANTITY = 19;
    public static final int SUPPLIER = 20;
    public static final int DELIVERYDATE = 21;
    public static final int DEACTIVATION = 22;
    public static final int INDEXNAME = 23;
    public static final int DELETELINE = 24;
    public static final int REQUISITIONTYPE = 25;
    public static final int CREATEDBY = 26;
    public static final int CREATIONDATE = 27;
    public static final int LASTUPDATEDBY = 28;
    public static final int LASTUPDATEDATE = 29;
    public static final int LASTUPDATELOGIN = 30;
    public static final int ISDEACTIVATIONRENDERED = 31;
    public static final int DELETEIMAGE = 32;
    public static final int ISSELECTED = 33;
    public static final int OBJECTVERSIONNUMBER = 34;
    public static final int REQITEMID = 35;
    public static final int REQHEADERNUM = 36;
    public static final int REQLINEQTY = 37;
    public static final int STATUS = 38;
    public static final int ISREADONLY = 39;
    public static final int ISRENDERED = 40;
    public static final int OPERATIONSEQNUM = 41;
    public static final int OPERATIONDESCRIPTION = 42;
    public static final int WIPENTITYID = 43;
    public static final int WIPENTITYNAME = 44;
    public static final int CFO = 45;
    public static final int MVZ = 46;
    public static final int ORIGWROFLAG = 47;
    public static final int WIPDATEREQUIRED = 48;
    public static final int WIPSUBINVENTORY = 49;
    public static final int WIPLOCATORID = 50;
    public static final int WIPGLDATE = 51;
    public static final int WIPBUYERNOTES = 52;
    public static final int WIPOLNUM = 53;
    public static final int WIPOLDATE = 54;
    public static final int WIPDUEDATE = 55;

    /**This is the default constructor (do not remove)
     */
    public Table5SourceVORowImpl() {
    }

    /**Gets Table5SourceEO entity object.
     */
    public Table5SourceEOImpl getTable5SourceEO() {
        return (Table5SourceEOImpl)getEntity(0);
    }

    /**Gets the attribute value for LINE_NUM using the alias name LineNum
     */
    public Number getLineNum() {
        return (Number)getAttributeInternal(LINENUM);
    }

    /**Sets <code>value</code> as attribute value for LINE_NUM using the alias name LineNum
     */
    public void setLineNum(Number value) {
        setAttributeInternal(LINENUM, value);
    }

    /**Gets the attribute value for ITEM_ID using the alias name ItemId
     */
    public Number getItemId() {
        return (Number)getAttributeInternal(ITEMID);
    }

    /**Sets <code>value</code> as attribute value for ITEM_ID using the alias name ItemId
     */
    public void setItemId(Number value) {
        setAttributeInternal(ITEMID, value);
    }

    /**Gets the attribute value for DESCRIPTIONS using the alias name Descriptions
     */
    public String getDescriptions() {
        return (String)getAttributeInternal(DESCRIPTIONS);
    }

    /**Sets <code>value</code> as attribute value for DESCRIPTIONS using the alias name Descriptions
     */
    public void setDescriptions(String value) {
        setAttributeInternal(DESCRIPTIONS, value);
    }

    /**Gets the attribute value for ITEM_CODE using the alias name ItemCode
     */
    public String getItemCode() {
        return (String)getAttributeInternal(ITEMCODE);
    }

    /**Sets <code>value</code> as attribute value for ITEM_CODE using the alias name ItemCode
     */
    public void setItemCode(String value) {
        setAttributeInternal(ITEMCODE, value);
    }

    /**Gets the attribute value for CATALOG_NUM using the alias name CatalogNum
     */
    public String getCatalogNum() {
        return (String)getAttributeInternal(CATALOGNUM);
    }

    /**Sets <code>value</code> as attribute value for CATALOG_NUM using the alias name CatalogNum
     */
    public void setCatalogNum(String value) {
        setAttributeInternal(CATALOGNUM, value);
    }

    /**Gets the attribute value for SUP_DESCRIPTION using the alias name SupDescription
     */
    public String getSupDescription() {
        return (String)getAttributeInternal(SUPDESCRIPTION);
    }

    /**Sets <code>value</code> as attribute value for SUP_DESCRIPTION using the alias name SupDescription
     */
    public void setSupDescription(String value) {
        setAttributeInternal(SUPDESCRIPTION, value);
    }

    /**Gets the attribute value for UOM using the alias name Uom
     */
    public String getUom() {
        return (String)getAttributeInternal(UOM);
    }

    /**Sets <code>value</code> as attribute value for UOM using the alias name Uom
     */
    public void setUom(String value) {
        setAttributeInternal(UOM, value);
    }

    /**Gets the attribute value for NEED_BY_DATE using the alias name NeedByDate
     */
    public Date getNeedByDate() {
        return (Date)getAttributeInternal(NEEDBYDATE);
    }

    /**Sets <code>value</code> as attribute value for NEED_BY_DATE using the alias name NeedByDate
     */
    public void setNeedByDate(Date value) {
        setAttributeInternal(NEEDBYDATE, value);
    }

    /**Gets the attribute value for QUANTITY using the alias name Quantity
     */
    public Number getQuantity() {
        return (Number)getAttributeInternal(QUANTITY);
    }

    /**Sets <code>value</code> as attribute value for QUANTITY using the alias name Quantity
     */
    public void setQuantity(Number value) {
        setAttributeInternal(QUANTITY, value);
    }

    /**Gets the attribute value for UNIT_PRICE using the alias name UnitPrice
     */
    public Number getUnitPrice() {
        return (Number)getAttributeInternal(UNITPRICE);
    }

    /**Sets <code>value</code> as attribute value for UNIT_PRICE using the alias name UnitPrice
     */
    public void setUnitPrice(Number value) {
        setAttributeInternal(UNITPRICE, value);
    }

    /**Gets the attribute value for SUPPLIER_ID using the alias name SupplierId
     */
    public Number getSupplierId() {
        return (Number)getAttributeInternal(SUPPLIERID);
    }

    /**Sets <code>value</code> as attribute value for SUPPLIER_ID using the alias name SupplierId
     */
    public void setSupplierId(Number value) {
        setAttributeInternal(SUPPLIERID, value);
    }

    /**Gets the attribute value for SOURCE_ORGANIZATION_ID using the alias name SourceOrganizationId
     */
    public Number getSourceOrganizationId() {
        return (Number)getAttributeInternal(SOURCEORGANIZATIONID);
    }

    /**Sets <code>value</code> as attribute value for SOURCE_ORGANIZATION_ID using the alias name SourceOrganizationId
     */
    public void setSourceOrganizationId(Number value) {
        setAttributeInternal(SOURCEORGANIZATIONID, value);
    }

    /**Gets the attribute value for DEST_ORGANIZATION_ID using the alias name DestOrganizationId
     */
    public Number getDestOrganizationId() {
        return (Number)getAttributeInternal(DESTORGANIZATIONID);
    }

    /**Sets <code>value</code> as attribute value for DEST_ORGANIZATION_ID using the alias name DestOrganizationId
     */
    public void setDestOrganizationId(Number value) {
        setAttributeInternal(DESTORGANIZATIONID, value);
    }

    /**Gets the attribute value for PREPARER_ID using the alias name PreparerId
     */
    public Number getPreparerId() {
        return (Number)getAttributeInternal(PREPARERID);
    }

    /**Sets <code>value</code> as attribute value for PREPARER_ID using the alias name PreparerId
     */
    public void setPreparerId(Number value) {
        setAttributeInternal(PREPARERID, value);
    }

    /**Gets the attribute value for DELIVER_TO_LOCATION_ID using the alias name DeliverToLocationId
     */
    public Number getDeliverToLocationId() {
        return (Number)getAttributeInternal(DELIVERTOLOCATIONID);
    }

    /**Sets <code>value</code> as attribute value for DELIVER_TO_LOCATION_ID using the alias name DeliverToLocationId
     */
    public void setDeliverToLocationId(Number value) {
        setAttributeInternal(DELIVERTOLOCATIONID, value);
    }

    /**Gets the attribute value for DELIVER_TO_REQUESTOR_ID using the alias name DeliverToRequestorId
     */
    public Number getDeliverToRequestorId() {
        return (Number)getAttributeInternal(DELIVERTOREQUESTORID);
    }

    /**Sets <code>value</code> as attribute value for DELIVER_TO_REQUESTOR_ID using the alias name DeliverToRequestorId
     */
    public void setDeliverToRequestorId(Number value) {
        setAttributeInternal(DELIVERTOREQUESTORID, value);
    }

    /**Gets the attribute value for ORG_ID using the alias name OrgId
     */
    public Number getOrgId() {
        return (Number)getAttributeInternal(ORGID);
    }

    /**Sets <code>value</code> as attribute value for ORG_ID using the alias name OrgId
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**Gets the attribute value for REQ_LINE_ID using the alias name ReqLineId
     */
    public Number getReqLineId() {
        return (Number)getAttributeInternal(REQLINEID);
    }

    /**Sets <code>value</code> as attribute value for REQ_LINE_ID using the alias name ReqLineId
     */
    public void setReqLineId(Number value) {
        //setAttributeInternal(REQLINEID, value);
    }

    /**Gets the attribute value for IS_PROCESSED using the alias name IsProcessed
     */
    public String getIsProcessed() {
        return (String)getAttributeInternal(ISPROCESSED);
    }

    /**Sets <code>value</code> as attribute value for IS_PROCESSED using the alias name IsProcessed
     */
    public void setIsProcessed(String value) {
        setAttributeInternal(ISPROCESSED, value);
    }

    /**Gets the attribute value for CS_AVAILABLE_QUANTITY using the alias name CsAvailableQuantity
     */
    public Number getCsAvailableQuantity() {
        return (Number)getAttributeInternal(CSAVAILABLEQUANTITY);
    }

    /**Sets <code>value</code> as attribute value for CS_AVAILABLE_QUANTITY using the alias name CsAvailableQuantity
     */
    public void setCsAvailableQuantity(Number value) {
        setAttributeInternal(CSAVAILABLEQUANTITY, value);
    }

    /**Gets the attribute value for SUPPLIER using the alias name Supplier
     */
    public String getSupplier() {
        return (String)getAttributeInternal(SUPPLIER);
    }

    /**Sets <code>value</code> as attribute value for SUPPLIER using the alias name Supplier
     */
    public void setSupplier(String value) {
        setAttributeInternal(SUPPLIER, value);
    }

    /**Gets the attribute value for DELIVERY_DATE using the alias name DeliveryDate
     */
    public Number getDeliveryDate() {
        return (Number)getAttributeInternal(DELIVERYDATE);
    }

    /**Sets <code>value</code> as attribute value for DELIVERY_DATE using the alias name DeliveryDate
     */
    public void setDeliveryDate(Number value) {
        setAttributeInternal(DELIVERYDATE, value);
    }

    /**Gets the attribute value for DEACTIVATION using the alias name Deactivation
     */
    public String getDeactivation() {
        return (String)getAttributeInternal(DEACTIVATION);
    }

    /**Sets <code>value</code> as attribute value for DEACTIVATION using the alias name Deactivation
     */
    public void setDeactivation(String value) {
        setAttributeInternal(DEACTIVATION, value);
    }

    /**Gets the attribute value for DELETE_LINE using the alias name DeleteLine
     */
    public String getDeleteLine() {
        return (String)getAttributeInternal(DELETELINE);
    }

    /**Sets <code>value</code> as attribute value for DELETE_LINE using the alias name DeleteLine
     */
    public void setDeleteLine(String value) {
        setAttributeInternal(DELETELINE, value);
    }

    /**Gets the attribute value for REQUISITION_TYPE using the alias name RequisitionType
     */
    public String getRequisitionType() {
        return (String)getAttributeInternal(REQUISITIONTYPE);
    }

    /**Sets <code>value</code> as attribute value for REQUISITION_TYPE using the alias name RequisitionType
     */
    public void setRequisitionType(String value) {
        setAttributeInternal(REQUISITIONTYPE, value);
    }

    /**Gets the attribute value for CREATED_BY using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for CREATION_DATE using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**Gets the attribute value for OBJECT_VERSION_NUMBER using the alias name ObjectVersionNumber
     */
    public Number getObjectVersionNumber() {
        return (Number)getAttributeInternal(OBJECTVERSIONNUMBER);
    }

    /**Sets <code>value</code> as attribute value for OBJECT_VERSION_NUMBER using the alias name ObjectVersionNumber
     */
    public void setObjectVersionNumber(Number value) {
        setAttributeInternal(OBJECTVERSIONNUMBER, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case LINENUM:
            return getLineNum();
        case ITEMID:
            return getItemId();
        case DESCRIPTIONS:
            return getDescriptions();
        case ITEMCODE:
            return getItemCode();
        case CATALOGNUM:
            return getCatalogNum();
        case SUPDESCRIPTION:
            return getSupDescription();
        case UOM:
            return getUom();
        case NEEDBYDATE:
            return getNeedByDate();
        case QUANTITY:
            return getQuantity();
        case UNITPRICE:
            return getUnitPrice();
        case SUPPLIERID:
            return getSupplierId();
        case SOURCEORGANIZATIONID:
            return getSourceOrganizationId();
        case DESTORGANIZATIONID:
            return getDestOrganizationId();
        case PREPARERID:
            return getPreparerId();
        case DELIVERTOLOCATIONID:
            return getDeliverToLocationId();
        case DELIVERTOREQUESTORID:
            return getDeliverToRequestorId();
        case ORGID:
            return getOrgId();
        case REQLINEID:
            return getReqLineId();
        case ISPROCESSED:
            return getIsProcessed();
        case CSAVAILABLEQUANTITY:
            return getCsAvailableQuantity();
        case SUPPLIER:
            return getSupplier();
        case DELIVERYDATE:
            return getDeliveryDate();
        case DEACTIVATION:
            return getDeactivation();
        case INDEXNAME:
            return getIndexName();
        case DELETELINE:
            return getDeleteLine();
        case REQUISITIONTYPE:
            return getRequisitionType();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case ISDEACTIVATIONRENDERED:
            return getIsDeactivationRendered();
        case DELETEIMAGE:
            return getDeleteImage();
        case ISSELECTED:
            return getIsSelected();
        case OBJECTVERSIONNUMBER:
            return getObjectVersionNumber();
        case REQITEMID:
            return getReqItemId();
        case REQHEADERNUM:
            return getReqHeaderNum();
        case REQLINEQTY:
            return getReqLineQty();
        case STATUS:
            return getStatus();
        case ISREADONLY:
            return getisReadOnly();
        case ISRENDERED:
            return getisRendered();
        case OPERATIONSEQNUM:
            return getOperationSeqNum();
        case OPERATIONDESCRIPTION:
            return getOperationDescription();
        case WIPENTITYID:
            return getWipEntityId();
        case WIPENTITYNAME:
            return getWipEntityName();
        case CFO:
            return getCfo();
        case MVZ:
            return getMvz();
        case ORIGWROFLAG:
            return getOrigWroFlag();
        case WIPDATEREQUIRED:
            return getWipDateRequired();
        case WIPSUBINVENTORY:
            return getWipSubinventory();
        case WIPLOCATORID:
            return getWipLocatorId();
        case WIPGLDATE:
            return getWipGlDate();
        case WIPBUYERNOTES:
            return getWipBuyerNotes();
        case WIPOLNUM:
            return getWipOlNum();
        case WIPOLDATE:
            return getWipOlDate();
        case WIPDUEDATE:
            return getWipDueDate();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case LINENUM:
            setLineNum((Number)value);
            return;
        case ITEMID:
            setItemId((Number)value);
            return;
        case DESCRIPTIONS:
            setDescriptions((String)value);
            return;
        case ITEMCODE:
            setItemCode((String)value);
            return;
        case CATALOGNUM:
            setCatalogNum((String)value);
            return;
        case SUPDESCRIPTION:
            setSupDescription((String)value);
            return;
        case UOM:
            setUom((String)value);
            return;
        case NEEDBYDATE:
            setNeedByDate((Date)value);
            return;
        case QUANTITY:
            setQuantity((Number)value);
            return;
        case UNITPRICE:
            setUnitPrice((Number)value);
            return;
        case SUPPLIERID:
            setSupplierId((Number)value);
            return;
        case SOURCEORGANIZATIONID:
            setSourceOrganizationId((Number)value);
            return;
        case DESTORGANIZATIONID:
            setDestOrganizationId((Number)value);
            return;
        case PREPARERID:
            setPreparerId((Number)value);
            return;
        case DELIVERTOLOCATIONID:
            setDeliverToLocationId((Number)value);
            return;
        case DELIVERTOREQUESTORID:
            setDeliverToRequestorId((Number)value);
            return;
        case ORGID:
            setOrgId((Number)value);
            return;
        case REQLINEID:
            setReqLineId((Number)value);
            return;
        case ISPROCESSED:
            setIsProcessed((String)value);
            return;
        case CSAVAILABLEQUANTITY:
            setCsAvailableQuantity((Number)value);
            return;
        case SUPPLIER:
            setSupplier((String)value);
            return;
        case DELIVERYDATE:
            setDeliveryDate((Number)value);
            return;
        case DEACTIVATION:
            setDeactivation((String)value);
            return;
        case INDEXNAME:
            setIndexName((String)value);
            return;
        case DELETELINE:
            setDeleteLine((String)value);
            return;
        case REQUISITIONTYPE:
            setRequisitionType((String)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        case ISSELECTED:
            setIsSelected((String)value);
            return;
        case OBJECTVERSIONNUMBER:
            setObjectVersionNumber((Number)value);
            return;
        case REQITEMID:
            setReqItemId((Number)value);
            return;
        case ISREADONLY:
            setisReadOnly((Boolean)value);
            return;
        case ISRENDERED:
            setisRendered((Boolean)value);
            return;
        case OPERATIONSEQNUM:
            setOperationSeqNum((Number)value);
            return;
        case OPERATIONDESCRIPTION:
            setOperationDescription((String)value);
            return;
        case WIPENTITYID:
            setWipEntityId((Number)value);
            return;
        case CFO:
            setCfo((String)value);
            return;
        case MVZ:
            setMvz((String)value);
            return;
        case WIPDATEREQUIRED:
            setWipDateRequired((Date)value);
            return;
        case WIPSUBINVENTORY:
            setWipSubinventory((String)value);
            return;
        case WIPLOCATORID:
            setWipLocatorId((Number)value);
            return;
        case WIPGLDATE:
            setWipGlDate((Date)value);
            return;
        case WIPBUYERNOTES:
            setWipBuyerNotes((String)value);
            return;
        case WIPOLNUM:
            setWipOlNum((String)value);
            return;
        case WIPOLDATE:
            setWipOlDate((Date)value);
            return;
        case WIPDUEDATE:
            setWipDueDate((Date)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute IsDeactivationRendered
     */
    public Boolean getIsDeactivationRendered() {
        //return (Boolean) getAttributeInternal(ISDEACTIVATIONRENDERED);
        return getDeactivation() != null ? true : false;
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IsDeactivationRendered
     */
    public void setIsDeactivationRendered(Boolean value) {
        setAttributeInternal(ISDEACTIVATIONRENDERED, value);
    }

    /**Gets the attribute value for the calculated attribute DeleteImage
     */
    public String getDeleteImage() {
        //return (String)getAttributeInternal(DELETEIMAGE);
        return "DeleteEnabled";
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DeleteImage
     */
    public void setDeleteImage(String value) {
        setAttributeInternal(DELETEIMAGE, value);
    }

    /**Gets the attribute value for the calculated attribute IsSelected
     */
    public String getIsSelected() {
        return (String) getAttributeInternal(ISSELECTED);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IsSelected
     */
    public void setIsSelected(String value) {
        setAttributeInternal(ISSELECTED, value);
    }

    /**Gets the attribute value for the calculated attribute IndexName
     */
    public String getIndexName() {
        return (String) getAttributeInternal(INDEXNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IndexName
     */
    public void setIndexName(String value) {
        setAttributeInternal(INDEXNAME, value);
    }


    /**Gets the attribute value for the calculated attribute ReqItemId
     */
    public Number getReqItemId() {
        return (Number) getAttributeInternal(REQITEMID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ReqItemId
     */
    public void setReqItemId(Number value) {
        setAttributeInternal(REQITEMID, value);
    }

    /**Gets the attribute value for the calculated attribute isSelect2
     */
    /*
    public String getisSelect2() {
        return (String) getAttributeInternal(ISSELECT2);
    }
    */

    /**Sets <code>value</code> as the attribute value for the calculated attribute isSelect2
     */
    /*
    public void setisSelect2(String value) {
        setAttributeInternal(ISSELECT2, value);
    }
    */

    /**Gets the attribute value for the calculated attribute isSelect2_1
     */
    /*
    public String getisSelect2_1() {
        return (String) getAttributeInternal(ISSELECT2_1);
    }
    */

    /**Sets <code>value</code> as the attribute value for the calculated attribute isSelect2_1
     */
    /*
    public void setisSelect2_1(String value) {
        setAttributeInternal(ISSELECT2_1, value);
    }
    */

    /**Gets the attribute value for the calculated attribute isSelect2_1_1
     */
     /*
    public String getisSelect2_1_1() {
        return (String) getAttributeInternal(ISSELECT2_1_1);
    }
    */

    /**Sets <code>value</code> as the attribute value for the calculated attribute isSelect2_1_1
     */
    /*
    public void setisSelect2_1_1(String value) {
        setAttributeInternal(ISSELECT2_1_1, value);
    }
    */


    /**Gets the attribute value for the calculated attribute ReqHeaderNum
     */
    public String getReqHeaderNum() {
        return (String) getAttributeInternal(REQHEADERNUM);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ReqHeaderNum
     */
    public void setReqHeaderNum(String value) {
        setAttributeInternal(REQHEADERNUM, value);
    }

    /**Gets the attribute value for the calculated attribute ReqLineQty
     */
    public Number getReqLineQty() {
        return (Number) getAttributeInternal(REQLINEQTY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ReqLineQty
     */
    public void setReqLineQty(Number value) {
        setAttributeInternal(REQLINEQTY, value);
    }

    /**Gets the attribute value for the calculated attribute Status
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**Gets the attribute value for the calculated attribute isReadOnly
     */
    public Boolean getisReadOnly() {
        return (Boolean) getAttributeInternal(ISREADONLY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute isReadOnly
     */
    public void setisReadOnly(Boolean value) {
        setAttributeInternal(ISREADONLY, value);
    }

    /**Gets the attribute value for the calculated attribute isRendered
     */
    public Boolean getisRendered() {
        return (Boolean) getAttributeInternal(ISRENDERED);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute isRendered
     */
    public void setisRendered(Boolean value) {
        setAttributeInternal(ISRENDERED, value);
    }

    /**Gets the attribute value for OPERATION_SEQ_NUM using the alias name OperationSeqNum
     */
    public Number getOperationSeqNum() {
        return (Number) getAttributeInternal(OPERATIONSEQNUM);
    }

    /**Sets <code>value</code> as attribute value for OPERATION_SEQ_NUM using the alias name OperationSeqNum
     */
    public void setOperationSeqNum(Number value) {
        setAttributeInternal(OPERATIONSEQNUM, value);
    }

    /**Gets the attribute value for WIP_ENTITY_ID using the alias name WipEntityId
     */
    public Number getWipEntityId() {
        return (Number) getAttributeInternal(WIPENTITYID);
    }

    /**Sets <code>value</code> as attribute value for WIP_ENTITY_ID using the alias name WipEntityId
     */
    public void setWipEntityId(Number value) {
        setAttributeInternal(WIPENTITYID, value);
    }

    /**Gets the attribute value for the calculated attribute WipEntityName
     */
    public String getWipEntityName() {
        return (String) getAttributeInternal(WIPENTITYNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute WipEntityName
     */
    public void setWipEntityName(String value) {
        setAttributeInternal(WIPENTITYNAME, value);
    }

    /**Gets the attribute value for CFO using the alias name Cfo
     */
    public String getCfo() {
        return (String) getAttributeInternal(CFO);
    }

    /**Sets <code>value</code> as attribute value for CFO using the alias name Cfo
     */
    public void setCfo(String value) {
        setAttributeInternal(CFO, value);
    }

    /**Gets the attribute value for MVZ using the alias name Mvz
     */
    public String getMvz() {
        return (String) getAttributeInternal(MVZ);
    }

    /**Sets <code>value</code> as attribute value for MVZ using the alias name Mvz
     */
    public void setMvz(String value) {
        setAttributeInternal(MVZ, value);
    }

    /**Gets the attribute value for the calculated attribute OrigWroFlag
     */
    public String getOrigWroFlag() {
        return (String) getAttributeInternal(ORIGWROFLAG);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute OrigWroFlag
     */
    public void setOrigWroFlag(String value) {
        setAttributeInternal(ORIGWROFLAG, value);
    }

    /**Gets the attribute value for WIP_DATE_REQUIRED using the alias name WipDateRequired
     */
    public Date getWipDateRequired() {
        return (Date) getAttributeInternal(WIPDATEREQUIRED);
    }

    /**Sets <code>value</code> as attribute value for WIP_DATE_REQUIRED using the alias name WipDateRequired
     */
    public void setWipDateRequired(Date value) {
        setAttributeInternal(WIPDATEREQUIRED, value);
    }

    /**Gets the attribute value for WIP_LOCATOR_ID using the alias name WipLocatorId
     */
    public Number getWipLocatorId() {
        return (Number) getAttributeInternal(WIPLOCATORID);
    }

    /**Sets <code>value</code> as attribute value for WIP_LOCATOR_ID using the alias name WipLocatorId
     */
    public void setWipLocatorId(Number value) {
        setAttributeInternal(WIPLOCATORID, value);
    }

    /**Gets the attribute value for WIP_SUBINVENTORY using the alias name WipSubinventory
     */
    public String getWipSubinventory() {
        return (String) getAttributeInternal(WIPSUBINVENTORY);
    }

    /**Sets <code>value</code> as attribute value for WIP_SUBINVENTORY using the alias name WipSubinventory
     */
    public void setWipSubinventory(String value) {
        setAttributeInternal(WIPSUBINVENTORY, value);
    }

    /**Gets the attribute value for the calculated attribute WipGlDate
     */
    public Date getWipGlDate() {
        return (Date) getAttributeInternal(WIPGLDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute WipGlDate
     */
    public void setWipGlDate(Date value) {
        setAttributeInternal(WIPGLDATE, value);
    }

    /**Gets the attribute value for the calculated attribute OperationDescription
     */
    public String getOperationDescription() {
        return (String) getAttributeInternal(OPERATIONDESCRIPTION);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute OperationDescription
     */
    public void setOperationDescription(String value) {
        setAttributeInternal(OPERATIONDESCRIPTION, value);
    }

    /**Gets the attribute value for the calculated attribute WipBuyerNotes
     */
    public String getWipBuyerNotes() {
        return (String) getAttributeInternal(WIPBUYERNOTES);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute WipBuyerNotes
     */
    public void setWipBuyerNotes(String value) {
        setAttributeInternal(WIPBUYERNOTES, value);
    }

    /**Gets the attribute value for the calculated attribute WipOlNum
     */
    public String getWipOlNum() {
        return (String) getAttributeInternal(WIPOLNUM);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute WipOlNum
     */
    public void setWipOlNum(String value) {
        setAttributeInternal(WIPOLNUM, value);
    }

    /**Gets the attribute value for the calculated attribute WipOlDate
     */
    public Date getWipOlDate() {
        return (Date) getAttributeInternal(WIPOLDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute WipOlDate
     */
    public void setWipOlDate(Date value) {
        setAttributeInternal(WIPOLDATE, value);
    }

    /**Gets the attribute value for the calculated attribute WipDueDate
     */
    public Date getWipDueDate() {
        return (Date) getAttributeInternal(WIPDUEDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute WipDueDate
     */
    public void setWipDueDate(Date value) {
        setAttributeInternal(WIPDUEDATE, value);
    }
}
