package xxpha.oracle.apps.icx.sn1041.server.common;

import oracle.apps.fnd.framework.OAViewCriteria;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface AnalogVO extends ViewObject {
    void initQuery(OAViewCriteria param);
}
