package xxpha.oracle.apps.icx.sn1041.server.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface SearchResultsVORow extends Row {
    String getDeactivation();
}
