SET TERMOUT  ON
SET ECHO     OFF
SET FEEDBACK ON
SET VERIFY   ON
SET PAUSE    OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE

SPOOL XX_SN1041_INSTALL_PATCH_3.log

begin
  xxpha_pnaumov_pkg.find_block_session(p_obj_name=>'XXPHA_SN1041%', p_kill_session=>'Y');
end;
/
SHO ERR

PROMPT UPDATE package XXPHA_EAM518_PKG
@EAM518/sql/XX_EAM518_PKG.pks
SHO ERR

PROMPT RECREATE PACKAGE SPECIFICATION XXPHA_SN1041_PKG
@XX_SN1041_PKG.pks
SHO ERR

@EAM518/sql/XX_EAM518_PKG.pkb
SHO ERR

@EAM517/sql/XX_EAM517_PKG.sql
SHO ERR

PROMPT CREATE MENU ENTRIES
@XX_SN1041_EAM_MENU_ENTRY.sql
SHO ERR

PROMPT ALTER TABLES
@XX_SN1041_ALTER_TBL.sql

PROMPT CREATE VIEW XXPHA_SN1041_WIP_ENTITY_V
@XX_SN1041_WIP_ENTITY_V.sql

PROMPT CREATE VIEW XXPHA_SN1041_EAM_SEARCH_V
@XX_SN1041_EAM_SEARCH_V.sql

PROMPT CREATE VIEW XXPHA_SN1041_SESSION_V
@XX_SN1041_SESSION_V.sql

PROMPT CREATE VIEW XXPHA_SN1041_STORE_LIST_EAM_V
@XX_SN1041_STORE_LIST_EAM_V.sql

PROMPT CREATE VIEW XXPHA_SN1041_PARAMETERS_V
@XX_SN1041_PARAMETERS_V.sql

PROMPT CREATE VIEW XXPHA_SN1041_EAM_REQ_TYPE_V
@XX_SN1041_EAM_REQ_TYPE_V.sql

PROMPT CREATE VIEW XXPHA_SN1041_ACTIVE_CART_V
@XX_SN1041_ACTIVE_CART_V.sql

@XX_SN1041_WIP_OPERATIONS_V.sql

@XX_SN1041_REQ_ITEMS_T.sql
@XX_SN1041_REQ_ITEMS.sql

@XX_SN1041_REQ_TEMP_T.sql

@XX_SN1041_EAM_DISTR_TEMP_T.sql

@XX_SN1041_WORKORDERS_LIST_V.sql

@XX_SN1041_EAM_V.sql

PROMPT RECREATE PACKAGE SPECIFICATION XXPHA_SN1041_EAM_PKG
@XX_SN1041_EAM_PKG.pks
SHO ERR

PROMPT RECREATE PACKAGE BODY XXPHA_SN1041_PKG
@XX_SN1041_PKG.pkb
SHO ERR

PROMPT RECOMPILE PACKAGE SPECIFICATION XXPHA_SN1041_CREATE_REQ_PKG
@XX_SN1041_CREATE_REQ_PKG.pck
SHO ERR

PROMPT RECOMPILE PACKAGE XXPHA_SN1041_LST_REQ_BSKT_PKG
@XX_SN1041_LST_REQ_BSKT_PKG.pks
SHO ERR

@XX_SN1041_EAM_PKG.pkb
SHO ERR

@XX_SN1041_LST_REQ_BSKT_PKG.pkb
SHO ERR

PROMPT ************************************************************
ALTER PACKAGE XXPHA_SN1041_LST_REQ_BSKT_PKG COMPILE BODY
/
SHO ERR

ALTER PACKAGE XXPHA_SN1041_CREATE_REQ_PKG COMPILE BODY
/
SHO ERR

ALTER PACKAGE XXPHA_SN1041_PKG COMPILE BODY
/
SHO ERR

PROMPT  ************************************************************ 

PROMPT CREATE FND MESSAGE
@XX_SN1041_CREATE_MESSAGES_1.sql
SHO ERR

PROMPT CREATE CONCURRENT
@XX_SN1041_EAM_CONC.sql
sho err

SPOOL OFF
EXIT
