SET TERMOUT  ON
SET ECHO     OFF
SET FEEDBACK ON
SET VERIFY   ON
SET PAUSE    OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE

SPOOL XX_SN1041_INSTALL_PATCH_4.log

begin
  xxpha_pnaumov_pkg.find_block_session(p_obj_name=>'XXPHA_SN1041%', p_kill_session=>'Y');
end;
/
SHO ERR

--PROMPT CREATE VIEW XXPHA_SN1041_EAM_SEARCH_V
--@XX_SN1041_EAM_SEARCH_V.sql

PROMPT RECREATE PACKAGE BODY XXPHA_SN1041_PKG
@XX_SN1041_PKG.pkb
SHO ERR

PROMPT RECOMPILE PACKAGE BODY XXPHA_SN1041_LST_REQ_BSKT_PKG
ALTER PACKAGE XXPHA_SN1041_LST_REQ_BSKT_PKG COMPILE BODY
/
SHO ERR


PROMPT RECOMPILE PACKAGE BODY XXPHA_SN1041_ELASTIC_PROXY_PKG
ALTER PACKAGE XXPHA_SN1041_ELASTIC_PROXY_PKG COMPILE BODY
/
SHO ERR

SPOOL OFF
EXIT
