SET TERMOUT  ON
SET ECHO     OFF
SET FEEDBACK ON
SET VERIFY   ON
SET PAUSE    OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE


PROMPT XX_SN1041_RUN_REQ_LINES.sql
@XX_SN1041_RUN_REQ_LINES.sql
SHO ERR
PROMPT XX_SN1041_RUN_REQ_LINES_V.sql
@XX_SN1041_RUN_REQ_LINES_V.sql
SHO ERR
PROMPT XX_SN1041_INNER_REQ_PKG.sql
@XX_SN1041_INNER_REQ_PKG.sql
SHO ERR
PROMPT XX_SN1041_INNER_REQ_CONC.sql
@XX_SN1041_INNER_REQ_CONC.sql
SHO ERR
