SET TERMOUT  ON
SET ECHO     OFF
SET FEEDBACK ON
SET VERIFY   ON
SET PAUSE    OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE

SPOOL XX_SN1041_INSTALL.log

begin
  xxpha_pnaumov_pkg.find_block_session(p_obj_name=>'XXPHA_SN775_ELASTIC_PROXY_PKG', p_kill_session=>'Y');
end;
/
SHO ERR

begin
  xxpha_pnaumov_pkg.find_block_session(p_obj_name=>'XXPHA_SN1041%', p_kill_session=>'Y');
end;
/
SHO ERR

PROMPT RECREATE PACKAGE XXPHA_SN775_ELASTIC_PROXY_PKG
@SN775/sql/XX_SN775_ELASTIC_PROXY_PKG.pck
SHO ERR

PROMPT CREATE TABLE XXPHA.XXPHA_SN1041_ITEM_SEARCH_RSLT
@XX_SN1041_ITEM_SEARCH_RLST.sql

PROMPT CREATE TABLE XXPHA.XXPHA_SN1041_REQ_ITEMS_T
@XX_SN1041_REQ_ITEMS_T.sql

PROMPT CREATE VIEW XXPHA.XXPHA_SN1041_REQ_ITEMS
@XX_SN1041_REQ_ITEMS.sql

PROMPT CREATE TABLE XXPHA.XXPHA_SN1041_SESSION
@XX_SN1041_SESSION.sql

PROMPT CREATE SEQUENCE XXPHA.XXPHA_SN1041_SESSION
@XX_SN1041_SESSION_S.sql

PROMPT CREATE VIEW XXPHA.XXPHA_SN1041_SESSION_V
@XX_SN1041_SESSION_V.sql

PROMPT CREATE VIEW XXPHA.XXPHA_SN1041_ACTIVE_CART_V
@XX_SN1041_ACTIVE_CART_V.sql

PROMPT CREATE PACKAGE SPECIFICATION XXPHA_SN1041_PKG
@XX_SN1041_PKG.pks
SHO ERR

PROMPT CREATE VIEW xxpha_sn1041_store_list_v
@XX_SN1041_STORE_LIST_V.sql

PROMPT CREATE VIEW XXPHA_SN1041_REQ_TYPE_V
@XX_SN1041_REQ_TYPE_V.sql

PROMPT CREATE VIEW XPHA_SN1041_SUBINV_V
@XX_SN1041_SUBINV_V.sql

PROMPT CREATE PROFILES
@XX_SN1041_ELASTIC_PROFILES.sql
SHO ERR

PROMPT CREATE PACKAGE XXPHA_SN1041_ELASTIC_PROXY_PKG
@XX_SN1041_ELASTIC_PROXY_PKG.pck
SHO ERR

PROMPT CREATE TABLE XXPHA.XXPHA_SN1041_REQ_TEMP_T
@XX_SN1041_REQ_TEMP_T.sql

PROMPT CREATE PACKAGE SPECIFICATION XXPHA_SN1041_LST_REQ_BSKT_PKG
@XX_SN1041_LST_REQ_BSKT_PKG.pks
SHO ERR

PROMPT CREATE PACKAGE XPHA_SN1041_CREATE_REQ_PKG
@XX_SN1041_CREATE_REQ_PKG.pck
SHO ERR

PROMPT CREATE PACKAGE BODY XXPHA_SN1041_LST_REQ_BSKT_PKG
@XX_SN1041_LST_REQ_BSKT_PKG.pkb
SHO ERR

PROMPT CREATE PACKAGE BODY XXPHA_SN1041_PKG
@XX_SN1041_PKG.pkb
SHO ERR

PROMPT CREATE GRANT
@XX_SN1041_GRANTS.sql

PROMPT CREATE FND_MESSAGES
@XX_SN1041_CREATE_MESSAGES.sql
SHO ERR

PROMPT CREATE OAF PERS
@XX_SN1041_OAF_PERS.sql

SPOOL OFF
EXIT
