SET TERMOUT  ON
SET ECHO     OFF
SET FEEDBACK ON
SET VERIFY   ON
SET PAUSE    OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE

SPOOL XX_SN1041_INSTALL_PATCH_13.log

begin
  xxpha_pnaumov_pkg.find_block_session(p_obj_name=>'XXPHA_SN1041%', p_kill_session=>'Y');
end;
/
PROMPT ALTER PACKAGE BODY XXPHA_SN1041_PKG
@XX_SN1041_PKG.pkb
SHO ERR