SET TERMOUT  ON
SET ECHO     OFF
SET FEEDBACK ON
SET VERIFY   ON
SET PAUSE    OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE

SPOOL XX_SN1041_INSTALL_PATCH_2.log

begin
  xxpha_pnaumov_pkg.find_block_session(p_obj_name=>'XXPHA_SN1041%', p_kill_session=>'Y');
end;
/
SHO ERR

PROMPT CREATE PACKAGE BODY XXPHA_SN1041_PKG
@XX_SN1041_PKG.pkb
SHO ERR

PROMPT RECOMPILE PACKAGE BODY XXPHA_SN1041_CREATE_REQ_PKG
ALTER PACKAGE XXPHA_SN1041_CREATE_REQ_PKG COMPILE BODY
/
SHO ERR

PROMPT CREATE 2 SN976 INDEXES
@SN976/sql/XX_SN976_ADD_IDX0.sql

SPOOL OFF
EXIT
