package xxpha.oracle.apps.icx.sn1041.server.client;

import oracle.jbo.client.remote.RowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SearchResultsVORowClient extends RowImpl {
    /**This is the default constructor (do not remove)
     */
    public SearchResultsVORowClient() {
    }


    public String getDeactivation() {
        return (String)getAttribute("Deactivation");
    }

    public Boolean getIsDeactRendender() {
        return (Boolean)getAttribute("IsDeactRendender");
    }
}
